//tealium universal tag - utag.subloader ut4.0.201702150824, Copyright 2017 Tealium.com Inc. All Rights Reserved.
if(typeof utag=='undefined')var utag={o:{}};utag.o["etnetera.demogram"]={sender:{},send:{},loader:{q:[],lc:0,f:{},p:0,ol:0,wq:[],ft:0,rf:0,ri:0,rp:0,rq:[],WQ:function(a,b,c,d){utag.DB('WQ:'+this.wq.length);c=true;try{this.GET()}catch(e){};var lq=[];for(a=0;a<this.wq.length;a++){b=this.wq[a];b.load=this.cfg[b.id].load;if(b.load>0){if(b.send){c=false;this.utag.send[b.id]=b;this.f[b.id]=0;}
lq.push(b);}}
if(c){d=false;for(b in utag.loader.GV(this.utag.send))d=true;if(c&&d)this.LOAD('WAIT_FORCE');}
this.wq=[];for(a=0;a<lq.length;a++){utag.DB('utag.loader.WAIT: loading '+lq[a].id);this.AS(lq[a])}},AS:function(a,b,c,d){this.utag.sender[a.id]=a;if(typeof a.src=='undefined'){a.src=this.utag.cfg.path+((typeof a.name!='undefined')?a.name:'utag.'+a.id+'.js')}
if(this.utag.cfg.v)a.src+=(a.src.indexOf('?')>0?'&':'?')+'utv='+this.utag.cfg.v;utag.rpt['sp_l_'+a.id+'_'+'etnetera.demogram']=a.src;b=document;if(a.load==2){b.write('<script id="'+a.id+'" src="'+a.src+'"></scr'+'ipt>')}else{if(b.createElement){c='utag_etnetera.demogram_'+a.id;if(!b.getElementById(c)){if(a.load==3){d=b.createElement('iframe');d.setAttribute('height','1');d.setAttribute('width','1');d.setAttribute('style','display:none');d.setAttribute('src',a.src)}else{d=b.createElement('script');d.language='javascript';d.type='text/javascript';d.src=a.src}
d.id=c;b.getElementsByTagName('head')[0].appendChild(d)}}}},LOAD:function(a,b,c,d){utag.DB('utag.loader.LOAD:'+a);if(this.f[a]==0){utag.DB('utag.loader.LOAD:add sender-'+a);this.f[a]=1;if(this.wq.length>0)return;for(b in utag.loader.GV(this.f)){if(this.f[b]==0)return};utag.DB('CLEAR FORCE');clearTimeout(utag.loader.ft);utag.DB('utag.handler.INIT');this.utag.handler.INIT()}}},view:function(a){this.handler.trigger('view',a)},link:function(a){this.handler.trigger('link',a)},handler:{base:"",df:{},o:{},send:{},iflag:0,INIT:function(a,b,c){this.iflag=1;this.trigger('view',utag.data)},test:function(){return 1},trigger:function(a,b,c,d){b=b||{};if(!this.iflag){this.utag.loader.q.push({a:a,b:b});return;}
for(c in utag.loader.GV(this.df)){if(typeof this.df[c]!="function"&&typeof b[c]=="undefined")b[c]=this.df[c]}
for(c=0;c<this.extend.length;c++){try{this.extend[c](a,b);utag.rpt['sp_ex_'+c+'_'+'etnetera.demogram']=0}catch(e){utag.rpt['sp_ex_'+c+'_'+'etnetera.demogram']=1}};for(c in utag.loader.GV(this.utag.send)){if(typeof this.utag.sender[c]!="undefined"){try{this.utag.sender[c].send(a,this.C(b));utag.rpt['sp_s_'+c+'_'+'etnetera.demogram']=0}catch(e){utag.rpt['sp_s_'+c+'_'+'etnetera.demogram']=1};utag.rpt.ts['sp_s_'+'etnetera.demogram']=new Date();utag.RP(utag.rpt);}}
c=this.base.split(",");for(d=0;d<c.length;d++){if(typeof b[c[d]]!="undefined")this.df[c[d]]=b[c[d]]}
this.o=b},C:function(a,b,c,d){b={};for(c in utag.loader.GV(a)){if(typeof a[c]!="function")b[c]=a[c]}
return b}}};utag.o["etnetera.demogram"].loader.utag=utag.o["etnetera.demogram"];utag.o["etnetera.demogram"].handler.utag=utag.o["etnetera.demogram"];utag.o["etnetera.demogram"].cfg={v:"ut4.0.201702150824",readywait:0,forcetimeout:3000,domain:utag.loader.lh(),path:"//tags.tiqcdn.com/utag/etnetera/demogram/prod/",utid:"etnetera/demogram/201702150823"};utag.o["etnetera.demogram"].cond={};utag.o["etnetera.demogram"].handler.extend=[];;utag.o["etnetera.demogram"].handler.cfg_extend=[];utag.o["etnetera.demogram"].loader.cfg={};utag.o["etnetera.demogram"].loader.SETFORCE=function(a){utag.DB('SETFORCE:'+a);if(this.ft>0)clearTimeout(this.ft);this.ft=(utag.cfg.forcetimeout!=0)?setTimeout(this.FORCE,utag.cfg.forcetimeout):0}
utag.o["etnetera.demogram"].loader.FORCE=function(a,b,c,d){a=this.utag.sender;b=this.f;utag.DB('FORCE');for(c in utag.loader.GV(b)){d=a[c].id;if(typeof b[c]!='undefined'&&b[c]==0){utag.DB('FORCEERROR:'+d);utag.rpt['sp_f_'+d+'_'+'etnetera.demogram']=1;delete this.utag.sender[d];delete this.utag.send[d];this.LOAD(d)}}}
utag.o["etnetera.demogram"].loader.INIT=function(a,b,c,d){if(this.ol==1)return-1;else this.ol=1;utag.rpt.ts['sp_i_'+'etnetera.demogram']=new Date();if(!utag.cfg.noload){try{this.GET();}catch(e){};var lq=[];for(a in utag.loader.GV(this.utag.loader.cfg)){b=this.utag.loader.cfg[a];b.id=a;if(b.wait==1){this.wq.push(b)}else if(b.load>0){if(b.send){this.utag.send[b.id]=b;this.f[b.id]=0}
lq.push(b);}}
for(a=0;a<lq.length;a++){utag.DB('utag.loader.INIT: loading '+b.id);this.AS(lq[a])}
if(this.wq.length>0)utag.loader.EV('','ready',function(a){utag.o["etnetera.demogram"].loader.WQ();utag.o["etnetera.demogram"].loader.SETFORCE('WAIT')});else if(lq.length==0)utag.o["etnetera.demogram"].handler.INIT();else this.SETFORCE('INIT')}
return 1};utag.o["etnetera.demogram"].cfg.readywait?utag.loader.EV('','ready',function(a){utag.DB('READY');utag.o["etnetera.demogram"].loader.INIT()}):utag.o["etnetera.demogram"].loader.INIT();try{utag.loader.LOAD("etnetera.demogram")}catch(e){}